### PR TITLE
Keep datatypes of defined values

### PR DESCRIPTION
**Pull request by StefanNeuser**
Hi @hawkeye64 , thank you for the helpful extension. Related to the issue here https://github.com/motdotla/dotenv/issues/51 i made some small changes to your package to keep datatypes.

### CODE REVIEW

**Comment by hawkeye64** [comment]
@StefanNeuser I just got back from 8 days vacation and am catching up. I have presentation at Quasar.conf tomorrow, so will look at this PR next week. I appreciate your patience and the work you put into the PR to make it better. Thanks! :heart:

**Comment by StefanNeuser** [comment]
Hi @hawkeye64 , how was the https://www.youtube.com/watch?v=6ZKBZ3k4Ebk for you? I'm a big fan of your work!

**Comment by hawkeye64** [comment]
@StefanNeuser I'm always nervous, no matter how many times I have done it. But, it was great to break the ice and get the first one done. Hopefully we can do this annually, and in the meantime, have online meetups as well.

Again, thanks for the PR. :)

**Comment by hawkeye64** [comment]
Released in v1.0.5

**Pull request merged**
