### PR TITLE
Added env_staging option

### PR DESCRIPTION
**Pull request by dalezak**
@hawkeye64 would this suffice for allowing `.env.staging` to work?

### CODE REVIEW

**Comment by hawkeye64** [comment]
Thanks for the PR :heart:

**Comment by dalezak** [comment]
No worries! Question, do you need to submit a new version before this becomes available?

I'm still getting the old version `@quasar/quasar-app-extension-dotenv@1.0.5`.

**Comment by hawkeye64** [comment]
@dalezak Yes, I have to publish it to NPM registery, of which I will be doing very shortly.

**Comment by dalezak** [comment]
Thanks @hawkeye64, I really appreciate it 🙏

**Comment by hawkeye64** [comment]
Sorry, had to revert this. I am glad the qenv app-extension is working out better for you tho.

**Pull request merged**
